spring.application.name=project

server.port= 9090

alphavantage.api.key = JQP7X52DHIF8C9KJ

spring.datasource.url= jdbc:mysql://localhost:3306/trading_platform

spring.datasource.username=root

spring.datasource.password= chetan@2004

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true